Controllers/CariPanelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using odev.Models.Siniflar;

namespace odev.Controllers
{
    public class CariPanelController : Controller
    {
        // GET: CariPanel
        Context c = new Context();
        [Authorize]
        public ActionResult Index()
        {
            var mail = (string)Session["CariMail"];
            var degerler = c.Carilers.FirstOrDefault(x => x.CariMail == mail);
            ViewBag.m = mail;
            return View(degerler);
        }
        [Authorize]
        public ActionResult Siparislerim()
        {
            var mail = (string)Session["CariMail"];
            var id = c.Carilers.Where(x => x.CariMail == mail.ToString()).Select(y => y.Cariid).FirstOrDefault();
            var degerler = c.SatisHarekets.Where(x => x.Cariid == id).ToList();
            return View(degerler);
        }
    }
}

Views/CariPanel/Index.cshtml
@model odev.Models.Siniflar.Cariler
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_CariLayout.cshtml";
}

<br />
@using (Html.BeginForm("Index2", "CariPanel", FormMethod.Post))
{
    <table class="table table-hover">
        <tr><td><label>Mail adresi: @HttpContext.Current.User.Identity.Name</label> </td></tr>
        <tr><td>@Html.TextBoxFor(x => x.CariAd, new { @class = "form-control" })</td></tr>
        <tr><td>@Html.TextBoxFor(x => x.CariSoyad, new { @class = "form-control" })</td></tr>
        <tr><td>@Html.TextBoxFor(x => x.CariSehir, new { @class = "form-control" })</td></tr>
        <tr><td>@Html.TextBoxFor(x => x.CariSifre, new { @class = "form-control" })</td></tr>
    </table>
    <button class="btn btn-warning">Bilgilerimi Güncelle</button>
}

Views/CariPanel/Siparislerim.cshtml
@using odev.Models.Siniflar
@model List<SatisHareket>
@{
    ViewBag.Title = "Siparislerim";
    Layout = "~/Views/Shared/_CariLayout.cshtml";
}

<h2>Siparislerim</h2>
<br />
<table class="table table-bordered">
    <tr>
        <th>Ürün Adı</th>
        <th>Fiyat</th>
        <th>Tarih</th>
    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <td>@x.Urun.UrunAd</td>
            <td>@x.Fiyat</td>
            <td>@Convert.ToDateTime(x.Tarih).ToString("dd/MM/yyyy")</td>
        </tr>
    }
</table>